### ISSUE TITLE
Beta testing of 2.0

### ISSUE THREAD

**Issue by roman-yagodin** [roman-yagodin/R7.Epsilon#143]
### Stage 1:

- [x] Update customization project.
- [x] Make R7.Zeta skin by renaming most "R7.Epsilon" strings.
- [x] Install beta skin on production site.
- [x] Copy customization resources into production manually.
- [x] Make demo pages with typography, skin variants, menu structure, containers.

### Stage 2:

- Get feedback from users.
- Extensive testing on real data.
- Update other extensions to use Bootstrap 4
- Test with Google Pagespeed.
- Ready SQL scripts to update Skin/Pane/Container for production website(s).

#### List of extensions to update for BS 4:

- [x] Survey (R7.Dnn.Survey)
- [x] R7.News
- [x] R7.Dnn.Extensions (PagingControl)
- [x] R7.Documents (should be OK, but need check)
- [x] R7.University
- [x] R7.MiniGallery (maybe need some shim CSS classes for images)
- [x] R7.Dnn.AddUser (check)
- [x] R7.Dnn.UserHtml (check)
- R7.HelpDesk?

### Deploy:

- Update skin on production website(s).
- Update customizations.
- Update other extensions.
- Apply SQL scripts.
- Update the home page.

**Comment by roman-yagodin** [comment]
During beta-test of R7.Epsilon 2.0, first response time is 11,23 sec. (average by 10 attempts). This probably caused by menu generation.

**Comment by roman-yagodin** [comment]
- Need make second menu column on mobile screen wider
- Opera, Android browsers replace dropdowns with something...
- Don't need to check for browser compatibility every time, also need to add "Got it!" button to warning and reword text to make more sane assumptions.
- Do something with breadcrumbs wrapping - separator should remain on previous line to make it look better.

**Comment by roman-yagodin** [comment]
- [ ] Reusable variant of `.skin-menu-parent-item` - link with chevrons

**Comment by roman-yagodin** [comment]
List of extensions to update for BS 4:

- R7.Documents (need check)
- R7.News
- R7.University
- R7.MiniGallery (maybe need some shim CSS classes for images)

**Comment by roman-yagodin** [comment]
#153

**Comment by roman-yagodin** [comment]
## RC

- [ ] Update social API versions
- [ ] Depend on R7.Dnn.Extensions
