### ISSUE TITLE
Bootstrap 4

### ISSUE THREAD

**Issue by roman-yagodin** [roman-yagodin/R7.Epsilon#67]
- [x] Switch to Bootstrap 4 CSS/JS
- [x] Drop Glyphicons in favor to Font Awesome, also #141
- [x] Review, simplify pane layouts
- [x] Bootstrap in the PopupSkin
- [x] Bootstrap via CDN or JS library? Stick to local version for now. Related issue #141
- [x] Color overrides #118
- [x] Bootstrap and DNN styles mix (e.g. in DNN edit forms, popups) - forms mostly looks OK now
